repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: master
  hooks:
    - id: trailing-whitespace
- repo: https://github.com/python/black
  rev: master
  hooks:
    - id: black
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: master
  hooks:
    - id: mypy
